# Generated by Django 3.0 on 2020-11-27 02:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('contest_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics/')),
                ('input_format', models.CharField(max_length=100)),
                ('output_format', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_contests', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
    ]
