# Generated by Django 3.0 on 2020-11-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='created',
        ),
    ]
