# Generated by Django 3.0 on 2020-11-27 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contests', '0002_remove_contests_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contests',
            name='input_format',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contests',
            name='output_format',
            field=models.CharField(max_length=500),
        ),
    ]
